export const APP_INIT                       = 'APP/INIT'
export const APP_INITS                      = 'APP/INITS'
export const APP_LOCAL                      = 'APP/LOCAL'
export const APP_CHECK                      = 'APP/CHECK'
export const APP_FLAG                       = 'APP/FLAG'
export const APP_ERR                        = 'APP/ERR'
export const APP_INIT_S                     = 'APP/INIT_S'
export const APP_AUTH_U                     = 'APP/INIT_U'
export const APP_LOAD                       = 'APP/LOAD'

export const APP_PARAMS                     = 'APP/PARAMS'

export const CATALOG_INIT                   = 'CATALOG/INIT'
export const CATALOG_SUBCATEGORIES          = 'CATALOG/SUBCATEGORIES'
export const CATALOG_PRODUCTS               = 'CATALOG/PRODUCTS'
export const CATALOG_PRDOUCT                = 'CATALOG/PRDOUCT'

export const CATALOG_LIST                   = 'CATALOG/LIST'
export const CATALOG_LIST_SUBCATEGORIES     = 'CATALOG/LIST_SUBCATEGORIES'
export const CATALOG_LIST_PRODUCTS          = 'CATALOG/LIST_PRODUCTS'

export const CARD_INIT_PRODUCTS             = 'INIT/PRODUCTS'
export const CARD_PRODUCT_ADD               = 'PRODUCT/ADD'
export const CARD_PRODUCT_DEL               = 'PRODUCT/DEL'
export const CARD_COUNTER_INCREMENT         = 'COUNTER/INCREMENT'
export const CARD_COUNTER_DECREMENT         = 'COUNTER/DECREMENT'
export const CARD_INCREMENT_COUNT           = 'CARD/INCREMENT'
export const CARD_DECREMENT_COUNT           = 'CARD/DECREMENT'
export const CARD_INIT_PRICE                = 'PRICE/INIT'
export const CARD_PRICE_ADD                 = 'PRICE/ADD'
export const CARD_PRICE_INCREMENT           = 'PRICE/INCREMENT'
export const CARD_PRICE_DECREMENT           = 'PRICE/DECREMENT'

export const DELIVERY                       = 'DELIVERY'
export const PAYMENT                        = 'PAYMENT'
export const CONTACTS                       = 'CONTACTS'
export const TOORDER                        = 'TOORDER'
export const DESCRIPTION                    = 'DESCRIPTION'


export const CATEGORIES_GET_CATEGORIES      = 'CATEGORIES/GET__CATEGORIES'
export const CATEGORIES_GET_SUBCATEGORIES   = 'CATEGORIES/GET_SUBCATEGORIES' 
export const CATEGORIES_DEL_CATEGORIES      = 'CATEGORIES/DEL__CATEGORIES'
export const CATEGORIES_DEL_SUBCATEGORIES   = 'CATEGORIES/DEL_SUBCATEGORIES' 
export const CATEGORIES_UPD_CATEGORIES      = 'CATEGORIES/UPD__CATEGORIES'
export const CATEGORIES_UPD_SUBCATEGORIES   = 'CATEGORIES/UPD_SUBCATEGORIES'

export const PRODUCT_ADD                    = 'PRODUCT/ADD'
export const PRODUCT_DEL                    = 'PRODUCT/DEL'
export const PRODUCT_SEARCH                 = 'PRODUCT/SEACRCH'
export const PRODUCT_GET_EDIT               = 'PRODUCT/GET_EDIT'
export const PRODUCT_ARR                    = 'PRODUCT/ARR'